import { AnimalRecord } from "@/lib/types";

export const initialAnimals: AnimalRecord[] = [
  {
    id: "matriz-01",
    nome: "Lote Aurora",
    especie: "Bovino",
    raca_matriz: "Girolando",
    idade_matriz: 4.8,
    peso_matriz_kg: 510,
    ecc_matriz: 3.5,
    numero_partos_matriz: 2,
    abortos_matriz: 0,
    dias_desde_ultimo_parto: 118,
    filhos_nascidos_matriz: 2,
    raca_macho: "Gir",
    idade_macho: 4.7,
    peso_macho_kg: 760,
    qualidade_semen_macho: 5,
    filhos_nascidos_macho: 18,
    parentesco_endogamia: 0.04,
  },
  {
    id: "matriz-02",
    nome: "Lote Horizonte",
    especie: "Bovino",
    raca_matriz: "Angus",
    idade_matriz: 5.1,
    peso_matriz_kg: 565,
    ecc_matriz: 3.2,
    numero_partos_matriz: 3,
    abortos_matriz: 1,
    dias_desde_ultimo_parto: 134,
    filhos_nascidos_matriz: 3,
    raca_macho: "Senepol",
    idade_macho: 5.4,
    peso_macho_kg: 880,
    qualidade_semen_macho: 4,
    filhos_nascidos_macho: 21,
    parentesco_endogamia: 0.06,
  },
  {
    id: "matriz-03",
    nome: "Lote Serra Clara",
    especie: "Caprino",
    raca_matriz: "Saanen",
    idade_matriz: 3.9,
    peso_matriz_kg: 61,
    ecc_matriz: 3.6,
    numero_partos_matriz: 2,
    abortos_matriz: 0,
    dias_desde_ultimo_parto: 92,
    filhos_nascidos_matriz: 3,
    raca_macho: "Boer",
    idade_macho: 3.6,
    peso_macho_kg: 89,
    qualidade_semen_macho: 4,
    filhos_nascidos_macho: 10,
    parentesco_endogamia: 0.03,
  },
];
