import { AnimalRecord } from "@/lib/types";

export const initialAnimals: AnimalRecord[] = [
  {
    id: "femea-01",
    nome: "Aurora 12",
    especie: "Bovino",
    sexo: "femea",
    raca: "Girolando",
    idade: 4.8,
    peso_kg: 510,
    filhos_nascidos: 2,
    parentesco_endogamia: 0.04,
    ecc: 3.5,
    numero_partos: 2,
    abortos: 0,
    dias_desde_ultimo_parto: 118,
    qualidade_semen: null,
  },
  {
    id: "femea-02",
    nome: "Horizonte 5",
    especie: "Bovino",
    sexo: "femea",
    raca: "Angus",
    idade: 5.1,
    peso_kg: 565,
    filhos_nascidos: 3,
    parentesco_endogamia: 0.06,
    ecc: 3.2,
    numero_partos: 3,
    abortos: 1,
    dias_desde_ultimo_parto: 134,
    qualidade_semen: null,
  },
  {
    id: "macho-01",
    nome: "Gir Campeao",
    especie: "Bovino",
    sexo: "macho",
    raca: "Gir",
    idade: 4.7,
    peso_kg: 760,
    filhos_nascidos: 18,
    parentesco_endogamia: 0.04,
    ecc: null,
    numero_partos: null,
    abortos: null,
    dias_desde_ultimo_parto: null,
    qualidade_semen: 5,
  },
  {
    id: "macho-02",
    nome: "Holandes Forte",
    especie: "Bovino",
    sexo: "macho",
    raca: "Holandes",
    idade: 5.4,
    peso_kg: 880,
    filhos_nascidos: 21,
    parentesco_endogamia: 0.05,
    ecc: null,
    numero_partos: null,
    abortos: null,
    dias_desde_ultimo_parto: null,
    qualidade_semen: 4,
  },
];
